#!/usr/bin/env sh
set -e
projectRoot="$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/.." || return; pwd)"

cd "${projectRoot}"

docker-compose \
  -f ./dream-league-api/docker-compose.yaml \
  -f ./dream-league-api/docker-compose.override.yaml \
  build $@

docker-compose \
  -f ./dream-league-web/docker-compose.yaml \
  -f ./dream-league-web/docker-compose.override.yaml \
  build $@
