#!/bin/bash
set -e

projectRoot="$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/.." || return; pwd)"

cd "${projectRoot}"; cd ./dream-league-api  && docker compose --profile app build
cd "${projectRoot}"; cd ./dream-league-web   && docker compose --profile app build
