#!/usr/bin/env sh
set -e
projectRoot="$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/.." || return; pwd)"

cd "${projectRoot}"

docker compose\
  -f ./dream-league-api/compose.yaml \
  -f ./dream-league-api/compose.override.yaml \
  down \
  $@

docker compose\
  -f ./dream-league-web/compose.yaml \
  -f ./dream-league-web/compose.override.yaml \
  down \
  $@
