#!/bin/bash
set -e

use_docker=false
extra_args=()

while [[ "$#" -gt 0 ]]; do
  case "$1" in
    --docker) use_docker=true ;;
    *) extra_args+=("$1") ;;
  esac
  shift
done

projectRoot="$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/.." || return; pwd)"

if [ "$use_docker" = true ]; then
  cd "${projectRoot}"; cd ./dream-league-api  && docker compose --profile app down "${extra_args[@]}"
  cd "${projectRoot}"; cd ./dream-league-web   && docker compose --profile app down "${extra_args[@]}"
else
  cd "${projectRoot}"; cd ./dream-league-api  && docker compose down "${extra_args[@]}"
fi
