#!/usr/bin/env sh
docker-compose \
  -f ../dream-league-api/docker-compose.yaml \
  -f ../dream-league-api/docker-compose.override.yaml \
  build $@

docker-compose \
  -f ../dream-league-web/docker-compose.yaml \
  -f ../dream-league-web/docker-compose.override.yaml \
  build $@
