#!/usr/bin/env sh
if [ -z "$(docker network ls --filter name=^dream-league$ --format={{.Name}})" ]; then
  echo "Creating dream-league Docker network"
  docker network create dream-league
fi

docker-compose \
  -f ../dream-league-api/docker-compose.yaml \
  -f ../dream-league-api/docker-compose.override.yaml \
  -f ../dream-league-api/docker-compose.link.yaml \
  up \
  --detach

docker-compose \
  -f ../dream-league-web/docker-compose.yaml \
  -f ../dream-league-web/docker-compose.override.yaml \
  -f ../dream-league-web/docker-compose.link.yaml \
  up \
  --detach
